/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.Controller;
import java.awt.event.KeyEvent;

/**
 *
 * @author fsegovia
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    private Controller _Controller;
    
    public MainFrame() {
        initComponents();
        _Controller = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jspTreeView = new javax.swing.JScrollPane();
        txaTreeView = new javax.swing.JTextArea();
        lblCommand = new javax.swing.JLabel();
        txtCommand = new javax.swing.JTextField();
        lblPath = new javax.swing.JLabel();
        jspLog = new javax.swing.JScrollPane();
        txaLog = new javax.swing.JTextArea();
        btnExecute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        txaTreeView.setEditable(false);
        txaTreeView.setBackground(new java.awt.Color(0, 0, 0));
        txaTreeView.setColumns(20);
        txaTreeView.setForeground(new java.awt.Color(51, 255, 0));
        txaTreeView.setRows(5);
        jspTreeView.setViewportView(txaTreeView);

        lblCommand.setText("Digite el comando");

        txtCommand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCommandKeyPressed(evt);
            }
        });

        lblPath.setText("Disco sin crear...");

        jspLog.setBackground(new java.awt.Color(0, 0, 0));

        txaLog.setEditable(false);
        txaLog.setBackground(new java.awt.Color(0, 0, 0));
        txaLog.setColumns(20);
        txaLog.setForeground(new java.awt.Color(51, 255, 0));
        txaLog.setRows(5);
        jspLog.setViewportView(txaLog);

        btnExecute.setText("Ejecutar");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jspTreeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCommand))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(txtCommand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExecute))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jspLog, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspTreeView, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(jspLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommand)
                    .addComponent(txtCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecute))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        excecuteCommand();
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void txtCommandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommandKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            excecuteCommand();
        }
    }//GEN-LAST:event_txtCommandKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecute;
    private javax.swing.JScrollPane jspLog;
    private javax.swing.JScrollPane jspTreeView;
    private javax.swing.JLabel lblCommand;
    private javax.swing.JLabel lblPath;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextArea txaLog;
    private javax.swing.JTextArea txaTreeView;
    private javax.swing.JTextField txtCommand;
    // End of variables declaration//GEN-END:variables


    public void refreshTreeView(String pContent) {
        txaTreeView.setText(pContent);
    }
    
    public void refreshPath(String pPath) {
        lblPath.setText(pPath);
    }
    
    public void addToLog(String pMessage) {
        String currentText = txaLog.getText();
        currentText += "\n" + pMessage;
        txaLog.setText(currentText);
    }
    
    public void excecuteCommand() {
        String command = txtCommand.getText();
        if(command.trim() != "") {
            addToLog("[->] Comando: "+ command);
            _Controller.processCommand(command);
            txtCommand.setText("");
        }
    }
}
